### ISSUE TITLE
Crash on client load

### ISSUE THREAD

**Issue by vladkar** [demiurghg/FusionEngine#7]
![image](https://cloud.githubusercontent.com/assets/12085093/11474372/d2f1e62a-9788-11e5-93bc-1da639134934.png)

**Comment by demiurghg** [comment]
Fixed. 
Do not use RenderSystem while loading game level because it is not thread safe.
Only content loading and creation is thread safe.
Populate ViewLayer and ViewLayerHDR on first call of FeedSnapshot.
